apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "nextcloud.fullname" . }}-collabora
  labels:
    app.kubernetes.io/name: {{ include "nextcloud.name" . }}-collabora
    helm.sh/chart: {{ include "nextcloud.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/component: app
  {{- if .Values.deploymentLabels }}
{{ toYaml .Values.deploymentLabels | indent 4 }}
  {{- end }}
  {{- if .Values.collabora.deploymentAnnotations }}
  annotations:
{{ toYaml .Values.collabora.deploymentAnnotations | indent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.collabora.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nextcloud.name" . }}-collabora
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/component: app
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nextcloud.name" . }}-collabora
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/component: app
        {{- if .Values.redis.enabled }}
        {{ template "nextcloud.redis.fullname" . }}-client: "true"
        {{- end }}
        {{- if .Values.podLabels }}
{{ toYaml .Values.collabora.podLabels | indent 8 }}
        {{- end }}
      {{- if .Values.collabora.podAnnotations }}
      annotations:
{{ toYaml .Values.collabora.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      {{- if .Values.collabora.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.collabora.image.pullSecrets }}
        - name: {{ . }}
      {{- end}}
      {{- end }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.collabora.image.repository }}:{{ .Values.collabora.image.tag }}"
        imagePullPolicy: {{ .Values.collabora.image.pullPolicy }}
        env:
          - name: extra_params
            value: "--o:ssl.enable=false --o:ssl.termination=true --o:welcome.enable=false"
          - name: domain
            value: "{{ .Values.nextcloud.host }}"
          - name: VIRTUAL_PROTO
            value: "https"
          - name: VIRTUAL_HOST
            value: "{{ .Values.collabora.ingress.host }}"
        ports:
        - name: http
          containerPort: 9980
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 1
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 1
        resources:
{{ toYaml .Values.collabora.resources | indent 10 }}
    {{- with .Values.collabora.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.collabora.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      {{- if .Values.rbac.enabled }}
      serviceAccountName: {{ .Values.rbac.serviceaccount.name }}
      {{- end }}
